### ISSUE TITLE
Screenshots Request

### ISSUE THREAD

**Issue by jonsafari** [wimstefan/mocp-themes#1]
It would be nice to have screenshots of the different themes, for people to preview them.

**Comment by wimstefan** [comment]
That's quite time consuming to achieve ... I'll see what I can do but won't promise anything ;-)

**Comment by leodelacruz** [comment]
There you go 
![138091-1](https://user-images.githubusercontent.com/8390315/36293873-4a59112a-12bb-11e8-8007-e7945de49a73.png)

**Comment by wimstefan** [comment]
Wonderful! The first step is made. Thank you for that 😏

**Comment by Serjeel-Ranjan-911** [comment]
@wimstefan  is this available to work?

**Comment by wimstefan** [comment]
> @wimstefan  is this available to work?

Not sure what you mean?

If the question is whether there will come more screenshots then my answer is "Not from my side."

I'm not using mocp anymore and leave the repository open and available for people who still have good use for it ...

**Comment by Serjeel-Ranjan-911** [comment]
@wimstefan  I mean I will do it if you accept PRs

**Comment by wimstefan** [comment]
> @wimstefan  I mean I will do it if you accept PRs

I sure do! That would be lovely 😊
New themes are certainly welcome as well 😏

**Comment by wimstefan** [comment]
Thanks to @Serjeel-Ranjan-911 we can close that now :)
